server:
  tomcat:
    uri-encoding: utf-8

spring:
  #   激活对应环境
  profiles:
    active: dev
 


---

server:
  port: 6666
  servlet:
    context-path: /
spring:
  profiles: prod

---
server:
  port: 6667
  servlet:
    context-path: /
spring:
  profiles: test

---
server:
  port: 6668
  servlet:
    context-path: /
spring:
  profiles: dev